version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://username:password@db:5432/taskdb
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taskdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d taskdb"]
      interval: 10s
      retries: 5
      start_period: 30s
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: